<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <!-- need for proper build -->
        <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    </PropertyGroup>

</Project>
